# Source Metadata
source_name: configcat
version: 1.0
authentication_required: true
api_types_available:
  - REST

# Client / Connection Config
client:
  base_url: https://api.configcat.com
  auth:
    type: basic
  headers:
    Accept: application/json

# Resources (per endpoint/object)
resources:
  - name: organizations
    endpoint:
      path: /organizations
      method: GET
      data_selector: organizations

  - name: organization_members
    endpoint:
      path: /organization_members
      method: GET
      data_selector: organization_members

  - name: products
    endpoint:
      path: /products
      method: GET
      data_selector: products

  - name: tags
    endpoint:
      path: /tags
      method: GET
      data_selector: tags

  - name: environments
    endpoint:
      path: /environments
      method: GET
      data_selector: environments

# Auth Details from Docs (for validation or onboarding)
auth_info:
  mentioned_objects:
    - Username
    - Password

# Known Quirks or Risks, Caveats
notes:
  - Only supports full refresh sync
  - Rate limits are enforced; 429 error code may be returned if limits are exceeded

# Troubleshooting & Error Patterns
errors:
  - 429: Throttle API calls or reduce frequency