resources:
- name: train_core
  endpoint:
    params:
      phases:
      - train
      - val
      num_epochs: 25
      save_model_dir: models
      verbose: false
      tmp_file_save_freq: 2
      print_info_batch_freq: 5
- name: MapImages
  endpoint:
    path: /mapreader/load/MapImages
    method: GET
    data_selector: images
    params: {}
- name: load_parents
  endpoint:
    path: /load_parents
    method: GET
    data_selector: None
    params: {}
- name: load_df
  endpoint:
    path: /load_df
    method: GET
    data_selector: None
    params: {}
- name: load_csv
  endpoint:
    path: /load_csv
    method: GET
    data_selector: None
    params: {}
- name: add_geo_info
  endpoint:
    path: /add_geo_info
    method: GET
    data_selector: None
    params: {}
- name: save_parents_as_geotiffs
  endpoint:
    path: /save_parents_as_geotiffs
    method: GET
    data_selector: None
    params: {}
- name: save_patches_as_geotiffs
  endpoint:
    path: /save_patches_as_geotiffs
    method: GET
    data_selector: None
    params: {}
- name: save_patches_to_geojson
  endpoint:
    path: /save_patches_to_geojson
    method: GET
    data_selector: None
    params: {}
- name: load_patches
  endpoint:
    path: /load_patches
    method: GET
    data_selector: None
    params: {}
- name: Annotator
  endpoint:
    path: /mapreader/annotate/annotator
    method: GET
    data_selector: records
    params: {}
- name: prepare_data
  endpoint:
    path: /mapreader/annotate/utils/prepare_data
    method: GET
    data_selector: records
    params: {}
- name: annotation_interface
  endpoint:
    path: /mapreader/annotate/utils/annotation_interface
    method: GET
    data_selector: records
    params: {}
- name: prepare_annotation
  endpoint:
    path: /mapreader/annotate/utils/prepare_annotation
    method: GET
    data_selector: records
    params: {}
- name: save_annotation
  endpoint:
    path: /mapreader/annotate/utils/save_annotation
    method: GET
    data_selector: records
    params: {}
- name: ClassifierContainer
  endpoint:
    path: /mapreader/classify/classifier/ClassifierContainer
    method: GET
- name: train_sample
  endpoint:
    path: /show_sample
    method: GET
    data_selector: sample_data
    params:
      set_name: train
      batch_number: 1
      print_batch_info: true
      figsize: (15, 10)
- name: validation_batch_info
  endpoint:
    path: /print_batch_info
    method: GET
    data_selector: batch_info
    params:
      set_name: train
- name: inference_sample_results
  endpoint:
    path: /show_inference_sample_results
    method: GET
    data_selector: inference_results
    params:
      num_samples: 6
      set_name: test
      min_conf: null
      max_conf: null
      figsize: (15, 15)
- name: save_object
  endpoint:
    path: /save
    method: POST
    data_selector: save_response
    params:
      save_path: default.obj
      force: false
- name: twoParallelModels
  endpoint:
    path: /mapreader/classify/custom_models/twoParallelModels
    method: GET
    data_selector: parameters
    params: {}
- name: PatchDataset
  endpoint:
    path: /mapreader/classify/datasets/PatchDataset
    method: GET
- name: PatchContextDataset
  endpoint:
    path: /mapreader/classify/datasets/PatchContextDataset
    method: GET
- name: AnnotationsLoader
  endpoint:
    path: /mapreader/classify/load_annotations
    method: GET
    data_selector: annotations
    params: {}
- name: Coordinate
  endpoint:
    path: /mapreader/download/data_structures/Coordinate
    method: GET
    data_selector: parameters
    params: {}
- name: GridIndex
  endpoint:
    path: /mapreader/download/data_structures/GridIndex
    method: GET
    data_selector: parameters
    params: {}
- name: GridBoundingBox
  endpoint:
    path: /mapreader/download/data_structures/GridBoundingBox
    method: GET
    data_selector: parameters
    params: {}
- name: downloader
  endpoint:
    path: /mapreader/download/downloader
    method: GET
    data_selector: maps
    params: {}
- name: create_polygon_from_latlons
  endpoint:
    path: /mapreader/download/downloader_utils/create_polygon_from_latlons
    method: POST
    data_selector: shapely Polygon
    params: {}
- name: create_line_from_latlons
  endpoint:
    path: /mapreader/download/downloader_utils/create_line_from_latlons
    method: POST
    data_selector: shapely LineString
    params: {}
- name: get_grid_bb_from_polygon
  endpoint:
    path: /mapreader/download/downloader_utils/get_grid_bb_from_polygon
    method: POST
    data_selector: GridBoundingBox
    params: {}
- name: get_polygon_from_grid_bb
  endpoint:
    path: /mapreader/download/downloader_utils/get_polygon_from_grid_bb
    method: POST
    data_selector: shapely.Polygon
    params: {}
- name: get_index_from_coordinate
  endpoint:
    path: /mapreader/download/downloader_utils/get_index_from_coordinate
    method: POST
    data_selector: GridIndex
    params: {}
- name: get_coordinate_from_index
  endpoint:
    path: /mapreader/download/downloader_utils/get_coordinate_from_index
    method: POST
    data_selector: Coordinate
    params: {}
- name: map_sheets
  endpoint:
    path: /map_sheets
    method: GET
    data_selector: features
- name: TileDownloader
  endpoint:
    path: /mapreader/download/tile_loading
    method: GET
- name: TileMerger
  endpoint:
    path: /mapreader/download/tile_merging
    method: GET
    data_selector: records
- name: extractGeoInfo
  endpoint:
    path: /mapreader/load/geo_utils/extractGeoInfo
    method: GET
    data_selector: list
    params: {}
- name: reproject_geo_info
  endpoint:
    path: /mapreader/load/geo_utils/reproject_geo_info
    method: GET
    data_selector: list
    params:
      target_crs: EPSG:4326
      calc_size_in_m: great-circle
- name: MapImages
  endpoint:
    path: /mapreader/load/images
    method: GET
- name: loader
  endpoint:
    path: /loader
    method: GET
    data_selector: MapImages
    params: {}
- name: load_patches
  endpoint:
    path: /load_patches
    method: GET
    data_selector: MapImages
    params: {}
- name: PatchDataFrame
  endpoint:
    path: /mapreader/process/post_process/PatchDataFrame
    method: GET
    data_selector: patch_df
    params: {}
- name: preprocess_all
  endpoint:
    path: preprocess_all
    method: POST
    data_selector: saved_paths
- name: preprocess
  endpoint:
    path: preprocess
    method: POST
    data_selector: resampled_image_path
- name: slice_serial
  endpoint:
    path: mapreader.utils.slice_parallel.slice_serial
    method: GET
    data_selector: records
    params:
      slice_size: 100
      slice_method: pixel
      output_dirname: slice_100_100
- name: images
  endpoint:
    path: ./small_mnist/*.png
    method: LOAD
    data_selector: my_files
- name: annotations
  endpoint:
    path: ./annotations_mnist/mnist_#kasra#.csv
    method: LOAD
    data_selector: annotated_images
- name: classifier
  endpoint:
    path: /classifier
    method: POST
    data_selector: model
    params: {}
- name: mnist_dataset
  endpoint:
    path: /api/mnist
    method: GET
    data_selector: data
    params: {}
- name: train
  endpoint:
    path: /train
    method: POST
    data_selector: results
    params:
      num_epochs: 5
      save_model_dir: ./models_mnist
      tensorboard_path: tboard_mnist
      tmp_file_save_freq: 2
      remove_after_load: false
      print_info_batch_freq: 5
- name: predictions
  endpoint:
    path: /predictions
    method: GET
    data_selector: predictions_df
- name: map_sheets
  endpoint:
    path: /geo.nls.uk/maps/os/1inch_2nd_ed/{z}/{x}/{y}.png
    method: GET
    data_selector: metadata
    params: {}
- name: parent_df
  endpoint:
    path: /parent_df
    method: GET
    data_selector: records
- name: patch_df
  endpoint:
    path: /patch_df
    method: GET
    data_selector: records
- name: annotations
  endpoint:
    path: ./annotations_one_inch/railspacerw#.csv
    method: GET
    data_selector: annotations
    params: {}
- name: train
  endpoint:
    path: /datasets/train
    method: GET
    data_selector: patch_df
- name: validate
  endpoint:
    path: /datasets/validate
    method: GET
    data_selector: patch_df
- name: test
  endpoint:
    path: /datasets/test
    method:
      GET: GET
    data_selector: patch_df
- name: patches
  endpoint:
    path: /inference/patches
    method: POST
    data_selector: records
- name: patch
  endpoint:
    path: /patches
    method: GET
    data_selector: patches
- name: parent
  endpoint:
    path: /parents
    method: GET
    data_selector: parents
- name: labels_map
  endpoint:
    path: /annotated_images/labels_map
    method: GET
    data_selector: labels_map
    params: {}
- name: dataloaders
  endpoint:
    path: /annotated_images/create_dataloaders
    method: POST
    data_selector: dataloaders
    params:
      batch_size: 16
- name: model_summary
  endpoint:
    path: /my_classifier/model_summary
    method: GET
    data_selector: model_summary
    params: {}
- name: train
  endpoint:
    path: /my_classifier/train
    method: POST
    data_selector: train_results
    params:
      num_epochs: 10
      tmp_file_save_freq: 2
      remove_after_load: false
      print_info_batch_freq: 5
- name: annotation_tasks
  endpoint:
    path: ./annotation_tasks.yaml
    method: GET
    data_selector: tasks
    params: {}
- name: annotations
  endpoint:
    path: ./annotations_phenotype_open_access/phenotype_test_#kasra#.csv
    method: GET
    data_selector: annotations
    params: {}
- name: parent_images
  endpoint:
    path: ./dataset/open_access_plant/*png
    method: GET
    data_selector: images
    params: {}
- name: patches
  endpoint:
    path: ./patches_50_pixel/*png
    method: GET
    data_selector: patches
    params: {}
- name: labels_map
  endpoint:
    path: /annotated_images/labels_map
    method: GET
    data_selector: labels_map
- name: PatchDataset
  endpoint:
    path: /path/to/patch/dataset
    method: GET
    data_selector: records
    params: {}
- name: parent_df
  endpoint:
    path: ./dataset/open_access_plant/*.png
    method: GET
    data_selector: records
    params: {}
- name: patch_df
  endpoint:
    path: ./patches_50_pixel/*png
    method: GET
    data_selector: records
    params: {}
- name: labels_map
  endpoint:
    path: annotated_images.labels_map
    method: GET
    data_selector: '{0: ''1'', 1: ''2''}'
- name: dataloaders
  endpoint:
    path: /annotated_images/create_dataloaders
    method: GET
    data_selector: batch_size
    params: {}
- name: labels_map
  endpoint:
    path: /annotated_images/labels_map
    method: GET
    data_selector: labels
    params: {}
- name: labels_map
  endpoint:
    path: annotated_images.labels_map
    method: GET
    data_selector: '{0: ''1'', 1: ''2''}'
- name: images
  endpoint:
    path: /load/images
    method: GET
- name: annotations
  endpoint:
    path: /annotations
    method: GET
- name: classifications
  endpoint:
    path: /classify
    method: POST
- name: PatchDataset
  endpoint:
    path: /api/patch_dataset
    method: POST
    data_selector: data
    params: {}
- name: labels_map
  endpoint:
    path: /annotated_images.labels_map
    method: GET
    data_selector: labels_map
- name: dataloaders
  endpoint:
    path: /annotated_images.create_dataloaders
    method: POST
    data_selector: dataloaders
    params:
      batch_size: 16
- name: model_summary
  endpoint:
    path: /my_classifier.model_summary
    method: GET
    data_selector: model_summary
- name: train
  endpoint:
    path: /my_classifier.train
    method: POST
    data_selector: train
    params:
      num_epochs: 10
      tmp_file_save_freq: 2
      remove_after_load: false
      print_info_batch_freq: 5
- name: image_patches
  endpoint:
    path: /images/patches
    method: GET
    data_selector: records
    params: {}
- name: predictions
  endpoint:
    path: /predictions
    method: POST
    data_selector: results
- name: annotations
  endpoint:
    path: ./annotations_phenotype_open_access/phenotype_test_#kasra#.csv
    method: GET
    data_selector: annotations
- name: patches
  endpoint:
    path: ./patches_50_pixel/*png
    method: GET
    data_selector: patches
- name: labels_map
  endpoint:
    path: /annotated_images/labels_map
    method: GET
    data_selector: labels_map
    params: {}
notes:
- You do not need to use the same method between steps.
- The conda package seems to be sensitive to the precise priority of the conda channels.
- It is possible to use non-georeferenced maps in MapReader, however none of the functionality
  around plotting patches based on geospatial coordinates will be possible.
- Your map images should be stored in a flat directory. They cannot be nested.
- Uses OAuth2 with refresh token — requires setup of connected app in api
- Some objects like Contact may return nulls in deeply nested fields
- sampler will only be applied to the training dataset (datasets[“train”])
- DataLoader by default constructs a index sampler that yields integral indices. To
  make it work with a map-style dataset with non-integral indices/keys, a custom sampler
  must be provided.
- Default sort order is ascending=True.
- Default is None.
- Annotator class for annotating patches with labels.
- DataLoader by default constructs an index sampler that yields integral indices.
- DEFAULT_TEMP_FOLDER is '_tile_cache/'
- DEFAULT_IMG_DOWNLOAD_FORMAT is 'png'
- DEFAULT_OUT_FOLDER is './'
- DEFAULT_IMG_STORE_FORMAT is ('png', 'PNG')
- Your metadata file must contain an column which contains the image IDs (filenames)
  of your images.
- For each image in the parents dictionary, this method calls _add_geo_info_id and
  coordinates (if present) to the image in the parent dictionary.
- This is an example to show how you can use MapReader on non-patchified datasets
- Using 'CrossEntropyLoss()' as criterion.
- It is possible to interrupt a training (using Kernel/Interrupt in Jupyter Notebook
  or ctrl+C).
- Using default sampler.
- Device is set to cpu
- User needs to edit the annotation_tasks.yaml file to define tasks and paths.
- This is an example of a non-geospatial use of the MapReader pipeline
- 'Each training step will pass: [''train'', ''val''].'
errors:
- 'FileNotFoundError: If the provided patch_df or parent_df file path does not exist'
- 'ValueError: If patch_df or parent_df is not a valid path to a CSV file or a pandas
  DataFrame'
auth_info:
  mentioned_objects: []
client:
  base_url: https://mapreader.readthedocs.io/en/latest/User-guide/Classify.html
source_metadata: null
