client:
  auth: 'The API requires HTTP Basic Authentication, where you must include the header
    `Authorization: Basic Sm9objpzZWNyZXQ=` which is the Base64-encoded form of `username:password`
    (for example, for username `John` and password `secret`, the encoding is `Sm9objpzZWNyZXQ=`);
    the login ID is managed via the Retarus EAS Portal.'
  most_recurring_base_url: https://api.us1.retarus.com
  paginator: Pagination is required to work with more than 1000 status reports, and
    there is no explicit pagination parameter; instead, you must delete processed
    reports to access the next set.
endpoints:
- 'endpoints source: https://docs.retarus.com/fax/fax-for-applications-rest-api-manual':
  - https://faxws.de2.retarus.com/rest/v1`
  - https://faxws.us2.retarus.com/rest/v1`
  - https://faxws-ha.us.retarus.com/rest/v1`
  - https://faxws.sg1.retarus.com/rest/v1/`
  - https://faxws-ha.de.retarus.com/rest/v1`
  - https://faxws.de1.retarus.com/rest/v1`
  - https://faxws.us1.retarus.com/rest/v1`
  - https://faxws.ch1.retarus.com/rest/v1/`
- 'endpoints source: https://docs.retarus.com/fax/polling-api':
  - /faxin/rest/v1/topics/jhk234509sdfD?fetch=10&timeout=60&id
  - /faxin/rest/v1/files/20.tif
  - /faxin/rest/v1/files/21.pdf
  - /faxin/rest/v1/topics/jhk234509sdfD?fetch=0&timeout=60&ids
- 'endpoints source: https://docs.retarus.com/fax/setting-up-actfax-server-for-retarus-cloud-fax':
  - https://`
- 'endpoints source: https://docs.retarus.com/fax/building-a-custom-retarus-cloud-fax-connector-on-s':
  - "https://api.openconnectors.eu10.ext.hana.ondemand.com/\u2026**"
  - https://faxws.retarus.com/rest/v1
- 'endpoints source: https://docs.retarus.com/fax/sap-integration-flows-with-open-connectors-on-btp':
  - https://api.openconnectors.eu10.ext.hana.ondemand.com/elements/api-v2
  - https://help.sap.com/doc/a56f52e1a58e4e2bac7f7adbf45b2e26/Cloud/it-IT/index.html
- 'endpoints source: https://docs.retarus.com/fax/integrating-hyland-onbase-with-cloud-fax':
  - https://support.hyland.com/search/all?query=sftp&value-filters=platform_custom~%2522OnBase%2522&content-lang=en-US
- 'endpoints source: https://docs.retarus.com/eas/directory-synchronization-dirsync':
  - https://dirfilter.retarus.com/dirsync/v1/upload/?type=m2f
  - https://dirfilter.retarus.com/dirsync/v1/upload/?type=m2s
  - https://dirfilter.retarus.com/dirsync/v1/upload/?type=f2m
- 'endpoints source: https://docs.retarus.com/fax/configuration-api':
  - https://fax-config.de2.retarus.com/v2
