resources:
- name: pets
  endpoint:
    path: /pets
    method: GET
    data_selector: items
- name: animals
  endpoint:
    path: /animals
    method: GET
- name: genericArrayComponent
  endpoint:
    path: /components/schemas/genericArrayComponent
    method: GET
- name: numberArray
  endpoint:
    path: /components/schemas/numberArray
    method: GET
- name: stringArray
  endpoint:
    path: /components/schemas/stringArray
    method: GET
- name: objWithTypedArray
  endpoint:
    path: /components/schemas/objWithTypedArray
    method: GET
- name: token
  endpoint:
    path: ''
    method: POST
    data_selector: ''
    params: {}
- name: username
  endpoint:
    path: ''
    method: GET
    data_selector: ''
    params: {}
- name: id
  endpoint:
    path: ''
    method: GET
    data_selector: ''
    params: {}
- name: freeForm
  endpoint:
    path: ''
    method: GET
    data_selector: ''
    params: {}
- name: coordinates
  endpoint:
    path: ''
    method: GET
    data_selector: ''
    params: {}
- name: response_array
  endpoint:
    path: /response/array
    method: GET
    data_selector: description
- name: response_string
  endpoint:
    path: /response/string
    method: GET
    data_selector: description
- name: response_plain_text
  endpoint:
    path: /response/plain_text
    method: GET
    data_selector: description
- name: response_no_return_value
  endpoint:
    path: /response/no_return_value
    method: POST
    data_selector: description
notes:
- Requires setup of connected app in API Hub
- Fast, easy and reliable testing for integrating web apps, APIs and microservices.
- Consumer-driven contract testing provides a guarantee that systems are compatible.
- Integrate with leading API gateways like AWS Gateway, Azure API Management, and
  Kong.
- Unlock advanced features and scale your API management with API Hub’s integrated
  solution.
errors:
- 'REQUEST_LIMIT_EXCEEDED: Throttle API calls or reduce frequency'
- 'QUERY_TIMEOUT: Break down filters or add selectivity'
- '401 Unauthorized: Recheck OAuth scopes or token expiration'
auth_info:
  mentioned_objects: []
client:
  base_url: https://api.smartbear.com
  headers:
    Accept: application/json
source_metadata: null
