# Source Metadata
source_name: productive
version: 1.0
authentication_required: true
api_types_available:
  - REST

# Client / Connection Config
client:
  base_url: https://app.productive.io
  auth:
    type: apikey
  headers:
    Accept: application/json

# Resources (per endpoint/object)
resources:
  - name: activities
    endpoint:
      path: /api/v1/activities
      method: GET
      data_selector: records

  - name: approval_policies
    endpoint:
      path: /api/v1/approval_policies
      method: GET
      data_selector: records

  - name: workflows
    endpoint:
      path: /api/v1/workflows
      method: GET
      data_selector: records

  - name: boards
    endpoint:
      path: /api/v1/boards
      method: GET
      data_selector: records

  - name: attachments
    endpoint:
      path: /api/v1/attachments
      method: GET
      data_selector: records

  - name: bookings
    endpoint:
      path: /api/v1/bookings
      method: GET
      data_selector: records

  - name: comments
    endpoint:
      path: /api/v1/comments
      method: GET
      data_selector: records

  - name: companies
    endpoint:
      path: /api/v1/companies
      method: GET
      data_selector: records

  - name: contact_entries
    endpoint:
      path: /api/v1/contact_entries
      method: GET
      data_selector: records

  - name: custom_field_options
    endpoint:
      path: /api/v1/custom_field_options
      method: GET
      data_selector: records

  - name: custom_fields
    endpoint:
      path: /api/v1/custom_fields
      method: GET
      data_selector: records

  - name: dashboards
    endpoint:
      path: /api/v1/dashboards
      method: GET
      data_selector: records

  - name: deal_statuses
    endpoint:
      path: /api/v1/deal_statuses
      method: GET
      data_selector: records

  - name: deals
    endpoint:
      path: /api/v1/deals
      method: GET
      data_selector: records

  - name: document_types
    endpoint:
      path: /api/v1/document_types
      method: GET
      data_selector: records

  - name: entitlements
    endpoint:
      path: /api/v1/entitlements
      method: GET
      data_selector: records

  - name: events
    endpoint:
      path: /api/v1/events
      method: GET
      data_selector: records

  - name: exchange_rates
    endpoint:
      path: /api/v1/exchange_rates
      method: GET
      data_selector: records

  - name: expenses
    endpoint:
      path: /api/v1/expenses
      method: GET
      data_selector: records

  - name: filters
    endpoint:
      path: /api/v1/filters
      method: GET
      data_selector: records

  - name: holiday_calendars
    endpoint:
      path: /api/v1/holiday_calendars
      method: GET
      data_selector: records

  - name: holidays
    endpoint:
      path: /api/v1/holidays
      method: GET
      data_selector: records

  - name: invoice_attributions
    endpoint:
      path: /api/v1/invoice_attributions
      method: GET
      data_selector: records

  - name: invoices
    endpoint:
      path: /api/v1/invoices
      method: GET
      data_selector: records

  - name: line_items
    endpoint:
      path: /api/v1/line_items
      method: GET
      data_selector: records

  - name: lost_reasons
    endpoint:
      path: /api/v1/lost_reasons
      method: GET
      data_selector: records

  - name: memberships
    endpoint:
      path: /api/v1/memberships
      method: GET
      data_selector: records

  - name: organizations
    endpoint:
      path: /api/v1/organizations
      method: GET
      data_selector: records

  - name: organization_memberships
    endpoint:
      path: /api/v1/organization_memberships
      method: GET
      data_selector: records

  - name: pages
    endpoint:
      path: /api/v1/pages
      method: GET
      data_selector: records

  - name: page_versions
    endpoint:
      path: /api/v1/page_versions
      method: GET
      data_selector: records

  - name: payment_reminder_sequences
    endpoint:
      path: /api/v1/payment_reminder_sequences
      method: GET
      data_selector: records

  - name: payment_reminders
    endpoint:
      path: /api/v1/payment_reminders
      method: GET
      data_selector: records

  - name: payments
    endpoint:
      path: /api/v1/payments
      method: GET
      data_selector: records

  - name: pipelines
    endpoint:
      path: /api/v1/pipelines
      method: GET
      data_selector: records

  - name: prices
    endpoint:
      path: /api/v1/prices
      method: GET
      data_selector: records

  - name: project_assignments
    endpoint:
      path: /api/v1/project_assignments
      method: GET
      data_selector: records

  - name: projects
    endpoint:
      path: /api/v1/projects
      method: GET
      data_selector: records

  - name: rate_cards
    endpoint:
      path: /api/v1/rate_cards
      method: GET
      data_selector: records

  - name: reports_booking-reports
    endpoint:
      path: /api/v1/reports_booking-reports
      method: GET
      data_selector: records

  - name: salaries
    endpoint:
      path: /api/v1/salaries
      method: GET
      data_selector: records

  - name: sections
    endpoint:
      path: /api/v1/sections
      method: GET
      data_selector: records

  - name: services
    endpoint:
      path: /api/v1/services
      method: GET
      data_selector: records

  - name: service_types
    endpoint:
      path: /api/v1/service_types
      method: GET
      data_selector: records

  - name: sessions
    endpoint:
      path: /api/v1/sessions
      method: GET
      data_selector: records

  - name: subsidiaries
    endpoint:
      path: /api/v1/subsidiaries
      method: GET
      data_selector: records

  - name: tags
    endpoint:
      path: /api/v1/tags
      method: GET
      data_selector: records

  - name: task_lists
    endpoint:
      path: /api/v1/task_lists
      method: GET
      data_selector: records

  - name: tax_rates
    endpoint:
      path: /api/v1/tax_rates
      method: GET
      data_selector: records

  - name: tasks
    endpoint:
      path: /api/v1/tasks
      method: GET
      data_selector: records

  - name: time_entries
    endpoint:
      path: /api/v1/time_entries
      method: GET
      data_selector: records

  - name: time_entry_versions
    endpoint:
      path: /api/v1/time_entry_versions
      method: GET
      data_selector: records

  - name: timers
    endpoint:
      path: /api/v1/timers
      method: GET
      data_selector: records

  - name: reports_timesheet_reports
    endpoint:
      path: /api/v1/reports_timesheet_reports
      method: GET
      data_selector: records

  - name: users
    endpoint:
      path: /api/v1/users
      method: GET
      data_selector: records

  - name: widgets
    endpoint:
      path: /api/v1/widgets
      method: GET
      data_selector: records

  - name: workflow_statuses
    endpoint:
      path: /api/v1/workflow_statuses
      method: GET
      data_selector: records

# Auth Details from Docs (for validation or onboarding)
auth_info:
  mentioned_objects:
    - API Key
    - Organization ID

# Known Quirks or Risks, Caveats
notes:
  - Uses API key authentication  requires setup from the settings page

# Troubleshooting & Error Patterns
errors: []