auth_info:
- information_source; https://training-course-material.com/training/REST_API:
  - OAuth 1 and OAuth 2 are supported authentication mechanisms. OAuth 2 does not
    require browser-based token assignment or cryptography (HTTPS is sufficient),
    supports token refreshing, and allows server-side request distribution. OAuth
    1 allows for long-lived access tokens. OAuth 2 implementations vary across providers
    like Facebook and Google.
  - 'OAuth 1.0 authentication is required, passed in the Authorization header with
    the following parameters: oauth_consumer_key, oauth_token, oauth_signature_method
    (HMAC-SHA1), oauth_signature, oauth_timestamp, oauth_nonce, and oauth_version
    (1.0). The Authorization header must be formatted as "OAuth realm=<realm>, oauth_consumer_key=<key>,
    oauth_token=<token>, oauth_signature_method=HMAC-SHA1, oauth_signature=<signature>,
    oauth_timestamp=<timestamp>, oauth_nonce=<nonce>, oauth_version=1.0".'
  - 'Twitter API uses Bearer token authentication. Pass the bearer token in the Authorization
    header as "Authorization: Bearer <BEARER_TOKEN>" when making requests to the Twitter
    API endpoints.'
  - 'Twitter API v2 uses Bearer token authentication. Include your bearer token in
    the Authorization header as "Authorization: Bearer <BEARER_TOKEN>" for all requests.
    Obtain a bearer token by registering your application and generating credentials
    through the Twitter Developer Portal.'
possible_base_urls:
- information_source; https://training-course-material.com/training/REST_API:
  - http://api.something.com
  - http://example.com/resources/
possible_endpoints:
- information_source; https://training-course-material.com/training/REST_API:
  - GET http://ulca.comule.com/ex1/index.php?method=hello
  - GET http://www.000webhost.com/
  - GET https://api.twitter.com/1.1/search/tweets.json
  - GET https://api.twitter.com/2/tweets/20
  - GET https://api.twitter.com/2/tweets/440322224407314432?expansions=author_id
  - GET https://api.twitter.com/2/tweets/440322224407314432?expansions=author_id,attachments.media_keys
  - GET https://api.twitter.com/labs/2/tweets/search
  - POST http://api.something.com/users/user
  - POST http://urls.api.twitter.com/1/urls/count.json
