auth_info:
- information_source; https://www.prodigi.com/print-api/docs/reference/:
  - 'The API uses API key authentication. Include your API key in the X-API-Key header
    with each request, for example X-API-Key: your-api-key.'
- information_source; https://www.prodigi.com/print-api/:
  - 'The Print API uses API key authentication. Include your API key in the X-API-Key
    header with each request, for example: X-API-Key: your-api-key.'
pagination_info:
- information_source; https://www.prodigi.com/print-api/docs/reference/:
  - The API uses offset-based pagination with a Skip query parameter. The response
    includes a hasMore boolean field indicating if more results exist, and a nextUrl
    field containing the complete URL for the next page of results. When hasMore is
    true, use the nextUrl to fetch the next batch of orders; stop paginating when
    hasMore is false.
possible_base_urls:
- information_source; https://www.prodigi.com/print-api/docs/reference/:
  - https://api.prodigi.com/v4.0/Orders/
  - https://api.sandbox.prodigi.com/v4.0
possible_endpoints:
- information_source; https://www.prodigi.com/print-api/docs/reference/:
  - GET /Orders/{prodigi_order_id}/actions
  - POST /actions/cancel
  - POST /v4.0/orders/{prodigi_order_id}/actions/cancel
- information_source; https://www.prodigi.com/print-api/:
  - POST https://api.sandbox.prodigi.com/v4.0/Orders/ord_123456/actions
