auth_info:
- information_source; https://developer.productive.io/:
  - Add your API token to the X-Auth-Token header for every request. The token is
    generated in the Productive application under Settings > API integrations > Generate
    new token. Additionally, include your organization ID in the X-Organization-Id
    header for every request. Resources are protected with authorization; successful
    authorization returns the resource, while unauthorized requests receive HTTP 403
    with an error message.
  - 'To authorize API requests, include an Authorization header with a Bearer token.
    Add the header Authorization: Bearer YOUR_API_TOKEN to each request, where YOUR_API_TOKEN
    is your API key obtained from your Productive account settings.'
- information_source; https://developer.productive.io/users.html:
  - Authentication is passed via a query parameter named token. An invalid or missing
    token results in a 401 Unauthenticated response with error code invalid_auth_token.
    Include the token parameter in the query string when making requests to the API.
pagination_info:
- information_source; https://developer.productive.io/companies.html:
  - 'Pagination uses query parameters page[number] and page[size] in the URL. The
    response includes links.first and links.last URLs, plus meta fields: current_page,
    total_pages, total_count, page_size (default 30), and max_page_size (200). Stop
    paginating when current_page reaches total_pages.'
- information_source; https://developer.productive.io/projects.html:
  - 'Pagination uses offset-based parameters: query parameters page (default 1) and
    page_size (default 30, max 200) control requests; responses include current_page,
    total_pages, total_count, and page_size fields to navigate results.'
- information_source; https://developer.productive.io/reports.html:
  - Pagination uses query parameters page and page_size (optional, default 30, max
    200). Response includes meta object with current_page, total_pages, total_count,
    page_size, and max_page_size fields to track pagination state.
  - Pagination uses query parameters page[number] and page[size] to request specific
    pages. Response includes links object with first and last URLs, and meta object
    with current_page, total_pages, total_count, page_size (default 30), and max_page_size
    (200). Stop paginating when current_page equals total_pages.
  - 'Pagination uses query parameters page[number] and page[size], with page[size]
    defaulting to 30 and having a maximum of 200. The response includes meta fields:
    current_page, total_pages, total_count, and page_size to track pagination state.'
possible_base_urls:
- information_source; https://developer.productive.io/:
  - https://api.productive.io/api/v2/
- information_source; https://developer.productive.io/companies.html:
  - http://api-test.productive.io/api/v2
possible_endpoints:
- information_source; https://developer.productive.io/:
  - DELETE https://api.productive.io/api/v2/workflow_statuses/{id}
  - DELETE https://api.productive.io/api/v2/workflows/{id}
  - GET https://api.productive.io/api/v2/workflow_statuses
  - GET https://api.productive.io/api/v2/workflow_statuses/{id}
  - GET https://api.productive.io/api/v2/workflows
  - GET https://api.productive.io/api/v2/workflows/{id}
  - PATCH https://api.productive.io/api/v2/workflow_statuses/{id}
  - PATCH https://api.productive.io/api/v2/workflows/{id}
  - POST https://api.productive.io/api/v2/workflow_statuses
  - POST https://api.productive.io/api/v2/workflows
