resources:
- name: version
  endpoint:
    path: /version
    method: GET
- name: matrix
  endpoint:
    path: /matrix
    method: GET
- name: organism
  endpoint:
    path: /organism
    method: GET
- name: vfp
  endpoint:
    path: /vfp
    method: POST
- name: news
  endpoint:
    path: /news
    method: GET
- name: auth_login
  endpoint:
    path: /auth/login
    method: POST
- name: auth_me
  endpoint:
    path: /auth/me
    method: GET
- name: tasks
  endpoint:
    path: /stats/tasks
    method: GET
- name: matrix
  endpoint:
    path: /matrix
    method: GET
    data_selector: content
- name: organism
  endpoint:
    path: /organism
    method: GET
    data_selector: content
- name: vfp
  endpoint:
    path: /vfp
    method: POST
    data_selector: content
- name: news
  endpoint:
    path: /news
    method: GET
    data_selector: content
notes:
- Uses OAuth2 with password — requires setup of client ID and secret
errors:
- '422: Validation Error'
auth_info:
  mentioned_objects:
  - Token
  - UserData
client:
  base_url: api
  auth:
    type: oauth2
    flow: password
    token_url: /auth/login
    client_id: client_id
    client_secret: client_secret
source_metadata: null
