auth_info:
- information_source; https://help.prodcamp.com/api/auth:
  - 'The ProdCamp API uses two authentication components: a Product ID sent via the
    X-ProductId request header (optional; defaults to first product if omitted), and
    an API key sent either as the apikey query parameter or the X-apikey request header.'
pagination_info:
- information_source; https://help.prodcamp.com/api/customers:
  - PageNumber and PageSize are optional query parameters for pagination. The response
    includes an items array containing paginated results. Use PageNumber to specify
    which page to retrieve and PageSize to control results per page. The NeedsCountInResponse
    optional parameter likely indicates whether total count should be included in
    the response.
  - Pagination is controlled via query parameters PageNumber and PageSize (both optional
    integers). The response includes an items array containing the paginated results.
    The NeedsCountInResponse boolean parameter can be used to request a count in the
    response, suggesting total count information is available when needed.
  - 'Pagination uses offset-based scheme with query parameters: limit (page size),
    offset (starting position). Response includes pagesCount, pageSize, currentPage,
    and totalItemsCount fields to indicate pagination state and construct subsequent
    requests.'
possible_base_urls:
- information_source; https://help.prodcamp.com/api/auth:
  - https://app.prodcamp.com/api/v1
- information_source; https://help.prodcamp.com/api/customers:
  - https://app.prodcamp.com
possible_endpoints:
- information_source; https://help.prodcamp.com/api/auth:
  - GET https://app.prodcamp.com/api/v1/feedbacks
- information_source; https://help.prodcamp.com/api/customers:
  - DELETE /api/v1/Customers/accounts/{id}
  - DELETE /api/v1/Customers/contacts/{id}
  - GET /api/v1/Customers/accounts
  - GET /api/v1/Customers/accounts/{id}
  - GET /api/v1/Customers/contacts
  - GET /api/v1/Customers/contacts/{id}
  - POST /api/v1/Customers/accounts
  - POST /api/v1/Customers/contacts
  - PUT /api/v1/Customers/accounts/{id}
