auth_info:
- information_source; https://api.producthunt.com/v2/docs:
  - Currently the API requires an access_token for authentication. Applications request
    OAuth2 tokens on behalf of users and must declare scopes (public, private, write)
    based on required permissions; by default apps have public read-only scope, and
    write access requires contacting Product Hunt at hello@producthunt.com. Send the
    access_token in requests to https://api.producthunt.com/v2/api/graphql (exact
    header/parameter name for token not fully specified in provided text).
- ? information_source; https://api.producthunt.com/v2/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user
  : - 'Product Hunt uses OAuth 2.0 authorization code flow. Redirect users to https://api.producthunt.com/v2/oauth/authorize
      with query parameters: client_id (your app ID), redirect_uri (callback URL),
      response_type=code, and scope (space-separated scopes like public, private,
      write). After user authorization, they are redirected back to your redirect_uri
      with an authorization code in the code parameter, which you then exchange for
      an access token in the oauth#token step. Writing on behalf of users requires
      app approval and public, private, and write scopes.'
- ? information_source; https://api.producthunt.com/v2/docs/oauth_user_authentication/oauth_test_add_the_access_token_as_header_to_any_request
  : - OAuth 2.0 bearer token authentication is required. Add an Authorization header
      with the value "Bearer your_access_token" to every request made to the API.
      The access_token should be obtained through the OAuth flow and included in the
      Authorization header along with the Bearer scheme.
possible_base_urls:
- information_source; https://api.producthunt.com/v2/docs:
  - https://api.producthunt.com/v2/api/graphql
- ? information_source; https://api.producthunt.com/v2/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user
  : - https://api.producthunt.com
possible_endpoints:
- information_source; https://api.producthunt.com/v2/docs:
  - POST https://api.producthunt.com/v2/api/graphql
- ? information_source; https://api.producthunt.com/v2/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user
  : - GET https://api.producthunt.com/v2/oauth/authorize
- ? information_source; https://api.producthunt.com/v2/docs/oauth_user_authentication/oauth_test_add_the_access_token_as_header_to_any_request
  : - POST /v2/api/graphql
