resources:
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: user
  endpoint:
    path: /api/v1/users
    method: GET
    data_selector: data
    params: {}
- name: order
  endpoint:
    path: /api/v1/orders
    method: GET
    data_selector: data
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: nfs-server
  endpoint:
    path: /nfs-server
    method: GET
    data_selector: architectures
    params: {}
- name: web-server
  endpoint:
    path: /web-server
    method: GET
    data_selector: architectures
    params: {}
- name: container-host
  endpoint:
    path: /container-host
    method: GET
    data_selector: architectures
    params: {}
- name: php-fpm
  endpoint:
    path: /php-fpm
    method: GET
    data_selector: variants
    params: {}
- name: varnish
  endpoint:
    path: /varnish
    method: GET
    data_selector: architectures
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
- name: canonicalize_javascript_libraries
  endpoint:
    path: /filter-canonicalize-js
    method: GET
    data_selector: description
- name: combine_css
  endpoint:
    path: /filter-css-combine
    method: GET
    data_selector: description
- name: convert_meta_tags
  endpoint:
    path: /filter-convert-meta-tags
    method: GET
    data_selector: description
- name: extend_cache
  endpoint:
    path: /filter-cache-extend
    method: GET
    data_selector: description
- name: flatten_css_imports
  endpoint:
    path: /filter-flatten-css-imports
    method: GET
    data_selector: description
- name: inline_css
  endpoint:
    path: /filter-css-inline
    method: GET
    data_selector: description
- name: inline_import_to_link
  endpoint:
    path: /filter-css-inline-import
    method: GET
    data_selector: description
- name: inline_javascript
  endpoint:
    path: /filter-js-inline
    method: GET
    data_selector: description
- name: insert_dns_prefetch
  endpoint:
    path: /filter-insert-dns-prefetch
    method: GET
    data_selector: description
- name: rewrite_css
  endpoint:
    path: /filter-css-rewrite
    method: GET
    data_selector: description
- name: rewrite_javascript
  endpoint:
    path: /filter-js-minify
    method: GET
    data_selector: description
- name: rewrite_style_attributes_with_url
  endpoint:
    path: /filter-rewrite-style-attributes
    method: GET
    data_selector: description
- name: rewrite_images
  endpoint:
    path: /filter-rewrite-images
    method: GET
    data_selector: description
- name: recompress_images
  endpoint:
    path: /filter-recompress-images
    method: GET
    data_selector: description
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: fetch_directives
  endpoint:
    path: /how-tos/web-controls/csp-create/
    method: GET
    data_selector: directives
    params: {}
- name: document_directives
  endpoint:
    path: /how-tos/web-controls/csp-create/
    method: GET
    data_selector: directives
    params: {}
- name: navigation_directives
  endpoint:
    path: /how-tos/web-controls/csp-create/
    method: GET
    data_selector: directives
    params: {}
- name: other_directives
  endpoint:
    path: /how-tos/web-controls/csp-create/
    method: GET
    data_selector: directives
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: create_sub_account
  endpoint:
    path: /v2/accounts
    method: POST
    data_selector: null
    params: {}
- name: get_user_auth
  endpoint:
    path: /v2/users/self/authorization
    method: GET
    data_selector: null
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: M1 EOL Patches
  endpoint:
    path: /reference/m1eol-patches/
    method: GET
    data_selector: patches
    params: {}
- name: Contact Support
  endpoint:
    path: /getting-started/support/
    method: GET
    data_selector: support_info
    params: {}
- name: Web Controls
  endpoint:
    path: /how-tos/web-controls/
    method: GET
    data_selector: web_controls_info
    params: {}
- name: Block Countries
  endpoint:
    path: /how-tos/security/block-countries/
    method: GET
    data_selector: block_countries_info
    params: {}
- name: Edit Whitelist
  endpoint:
    path: /how-tos/security/whitelist/
    method: GET
    data_selector: whitelist_info
    params: {}
- name: Edit Blacklist
  endpoint:
    path: /how-tos/security/blacklist/
    method: GET
    data_selector: blacklist_info
    params: {}
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
- name: patch_12
  endpoint:
    path: /m1-patches/webscale-m1-opensource-12.patch.zip
    method: GET
    data_selector: records
- name: patch_13
  endpoint:
    path: /m1-patches/webscale-m1-opensource-13.patch.zip
    method: GET
    data_selector: records
- name: patch_14
  endpoint:
    path: /m1-patches/webscale-m1-opensource-14.patch.zip
    method: GET
    data_selector: records
- name: patch_15
  endpoint:
    path: /m1-patches/webscale-m1-opensource-15.patch.zip
    method: GET
    data_selector: records
- name: patch_16
  endpoint:
    path: /m1-patches/webscale-m1-opensource-16.patch.zip
    method: GET
    data_selector: records
- name: patch_17
  endpoint:
    path: /m1-patches/webscale-m1-opensource-17.patch.zip
    method: GET
    data_selector: records
- name: patch_18
  endpoint:
    path: /m1-patches/webscale-m1-opensource-18.patch.zip
    method: GET
    data_selector: records
- name: patch_19
  endpoint:
    path: /m1-patches/webscale-m1-opensource-19.patch.zip
    method: GET
    data_selector: records
- name: patch_20
  endpoint:
    path: /m1-patches/webscale-m1-opensource-20.patch.zip
    method: GET
    data_selector: records
- name: patch_21
  endpoint:
    path: /m1-patches/webscale-m1-opensource-21.patch.zip
    method: GET
    data_selector: records
- name: patch_22
  endpoint:
    path: /m1-patches/webscale-m1-opensource-22.patch.zip
    method: GET
    data_selector: records
- name: patch_23
  endpoint:
    path: /m1-patches/webscale-m1-opensource-23.patch.zip
    method: GET
    data_selector: records
- name: patch_24
  endpoint:
    path: /m1-patches/webscale-m1-opensource-24.patch.zip
    method: GET
    data_selector: records
- name: patch_25
  endpoint:
    path: /m1-patches/webscale-m1-opensource-25.patch.zip
    method: GET
    data_selector: records
- name: patch_26
  endpoint:
    path: /m1-patches/webscale-m1-opensource-26.patch.zip
    method: GET
    data_selector: records
- name: patch_27
  endpoint:
    path: /m1-patches/webscale-m1-opensource-27.patch.zip
    method: GET
    data_selector: records
- name: patch_28
  endpoint:
    path: /m1-patches/webscale-m1-opensource-28.patch.zip
    method: GET
    data_selector: records
- name: patch_29
  endpoint:
    path: /m1-patches/webscale-m1-opensource-29-v2.patch.zip
    method: GET
    data_selector: records
- name: patch_30
  endpoint:
    path: /m1-patches/webscale-m1-opensource-30.patch.zip
    method: GET
    data_selector: records
- name: patch_31
  endpoint:
    path: /m1-patches/webscale-m1-opensource-31.patch.zip
    method: GET
    data_selector: records
- name: patch_32
  endpoint:
    path: /m1-patches/webscale-m1-opensource-32.patch.zip
    method: GET
    data_selector: records
- name: patch_33
  endpoint:
    path: /m1-patches/webscale-m1-opensource-33.patch.zip
    method: GET
    data_selector: records
- name: patch_34
  endpoint:
    path: /m1-patches/webscale-m1-opensource-34.patch.zip
    method: GET
    data_selector: records
- name: patch_35
  endpoint:
    path: /m1-patches/webscale-m1-opensource-35.patch.zip
    method: GET
    data_selector: records
- name: patch_36
  endpoint:
    path: /m1-patches/webscale-m1-opensource-36.patch.zip
    method: GET
    data_selector: records
- name: patch_37
  endpoint:
    path: /m1-patches/webscale-m1-opensource-37.patch.zip
    method: GET
    data_selector: records
- name: patch_38
  endpoint:
    path: /m1-patches/webscale-m1-opensource-38.patch.zip
    method: GET
    data_selector: records
- name: patch_39
  endpoint:
    path: /m1-patches/webscale-m1-opensource-39.patch.zip
    method: GET
    data_selector: records
- name: patch_40
  endpoint:
    path: /m1-patches/webscale-m1-opensource-40.patch.zip
    method: GET
    data_selector: records
- name: patch_41
  endpoint:
    path: /m1-patches/webscale-m1-opensource-41.patch
    method: GET
    data_selector: records
- name: patch_42
  endpoint:
    path: /m1-patches/webscale-m1-opensource-42.patch
    method: GET
    data_selector: records
- name: patch_43
  endpoint:
    path: /m1-patches/webscale-m1-opensource-43.patch
    method: GET
    data_selector: records
- name: patch_44
  endpoint:
    path: /m1-patches/webscale-m1-opensource-44.patch
    method: GET
    data_selector: records
- name: patch_45
  endpoint:
    path: /m1-patches/webscale-m1-opensource-45.patch
    method: GET
    data_selector: records
- name: patch_46
  endpoint:
    path: /m1-patches/webscale-m1-opensource-46.patch
    method: GET
    data_selector: records
- name: patch_47
  endpoint:
    path: /m1-patches/webscale-m1-opensource-47.patch
    method: GET
    data_selector: records
- name: patch_48
  endpoint:
    path: /m1-patches/webscale-m1-opensource-48.patch
    method: GET
    data_selector: records
- name: patch_49
  endpoint:
    path: /m1-patches/webscale-m1-opensource-49.patch
    method: GET
    data_selector: records
- name: patch_50
  endpoint:
    path: /m1-patches/webscale-m1-opensource-50.patch
    method: GET
    data_selector: records
- name: patch_51
  endpoint:
    path: /m1-patches/webscale-m1-opensource-51.patch
    method: GET
    data_selector: records
- name: patch_52
  endpoint:
    path: /m1-patches/webscale-m1-opensource-52.patch
    method: GET
    data_selector: records
- name: patch_53
  endpoint:
    path: /m1-patches/webscale-m1-opensource-53.patch
    method: GET
    data_selector: records
- name: patch_54
  endpoint:
    path: /m1-patches/webscale-m1-opensource-54.patch
    method: GET
    data_selector: records
- name: patch_55
  endpoint:
    path: /m1-patches/webscale-m1-opensource-55.patch
    method: GET
    data_selector: records
- name: patch_56
  endpoint:
    path: /m1-patches/webscale-m1-opensource-56.patch
    method: GET
    data_selector: records
- name: patch_57
  endpoint:
    path: /m1-patches/webscale-m1-opensource-57.patch
    method: GET
    data_selector: records
- name: patch_58
  endpoint:
    path: /m1-patches/webscale-m1-opensource-58.patch
    method: GET
    data_selector: records
- name: patch_59
  endpoint:
    path: /m1-patches/webscale-m1-opensource-59.patch
    method: GET
    data_selector: records
- name: patch_60
  endpoint:
    path: /m1-patches/webscale-m1-opensource-60.patch
    method: GET
    data_selector: records
- name: patch_61
  endpoint:
    path: /m1-patches/webscale-m1-opensource-61.patch
    method: GET
    data_selector: records
- name: patch_62
  endpoint:
    path: /m1-patches/webscale-m1-opensource-62.patch
    method: GET
    data_selector: records
- name: patch_63
  endpoint:
    path: /m1-patches/webscale-m1-opensource-63.patch
    method: GET
    data_selector: records
- name: patch_64
  endpoint:
    path: /m1-patches/webscale-m1-opensource-64.patch
    method: GET
    data_selector: records
- name: patch_65
  endpoint:
    path: /m1-patches/webscale-m1-opensource-65.patch
    method: GET
    data_selector: records
- name: patch_66
  endpoint:
    path: /m1-patches/webscale-m1-opensource-66.patch
    method: GET
    data_selector: records
- name: patch_67
  endpoint:
    path: /m1-patches/webscale-m1-opensource-67.patch
    method: GET
    data_selector: records
- name: campaign_member
  endpoint:
    path: /services/data/vXX.X/sobjects/CampaignMember
    method: GET
    data_selector: records
    params:
      incremental: updated_at
- name: contact
  endpoint:
    path: /services/data/vXX.X/sobjects/Contact
    method: GET
    data_selector: records
    params: {}
notes:
- Uses OAuth2 with refresh token — requires setup of connected app in api
- Some objects like Contact may return nulls in deeply nested fields
- Normal support requests should be sent to support@webscalenetworks.com
- Critical requests should be sent to critical@webscalenetworks.com
- Some or all of the following may be required, depending upon your organization.
- Some or all of the following may be required, depending upon your application’s
  configuration.
- Since this deployment process is new, not all existing customer implementations
  are designed to use it.
- Docker container images deployed on Webscale are deployed as read-only, to help
  ensure the stability and integrity of the production environment.
- You may need to upgrade your environment if you don’t see any Git branch tags [*branch-branchname*].
- Public key authentication is enforced for accessing the dataserver.
- Some objects may return nulls in deeply nested fields
- Requires OAuth2 setup for accessing user data
- Ensure all tokens are correctly set in secrets
- EOL and unsupported upstream for PHP 7.4.
- Alpine variants omit the OS specification.
- Uses OAuth2 with refresh token — requires setup of connected app in webscale
- This filter exists primarily to ensure that other filters have a place to insert
  new tags in the head, or that trigger on the closing-tag of the head to perform
  some other action.
- This capability is only available through the Webscale API.
- The parent of the sub-account is inferred from the account in which you are authenticated.
- M1 Open-Source customers have a 30 day SLA on availability of patches and M1 Commerce
  customers have 60-day SLA on availability of patches.
- Webscale will have an M1 base ruleset ready and enabled to protect M1 applications.
- 'Known Issue: Applying this patch might fail because there are versions of Magento
  in circulation that use \r\n line breaks instead of \n line breaks for certain files.'
- After confirming the site appears to be working as expected, and Webscale Control
  Panel access is sent, Webscale will request testing by the store owner and/or developers.
- It is recommended to schedule the final migration for a low traffic/off-hours time
  to minimize impact to your customers.
errors:
- 'REQUEST_LIMIT_EXCEEDED: Throttle API calls or reduce frequency'
- 'QUERY_TIMEOUT: Break down filters or add selectivity'
- '401 Unauthorized: Recheck OAuth scopes or token expiration'
- 'INVALID_CREDENTIALS: Check your OAuth token and client credentials'
- 'NOT_FOUND: Verify the endpoint path and parameters'
- '429 Too Many Requests: Reduce the frequency of API calls'
- '409: sub-account name already in use'
- 'RCE: Remote code execution vulnerability'
auth_info:
  mentioned_objects:
  - OauthToken
  - AuthProvider
  - NamedCredential
client:
  base_url: https://support.webscalenetworks.com
source_metadata: null
