resources:
- name: monitoring_stations
  endpoint:
    path: /hydrology/id/stations
    method: GET
    data_selector: items
    params:
      _limit: '100'
- name: measures
  endpoint:
    path: /hydrology/id/measures
    method: GET
    data_selector: items
    params:
      _limit: '10'
- name: readings
  endpoint:
    path: /hydrology/data/readings
    method: GET
    data_selector: items
    params:
      _limit: '2000000'
- name: monitoring_station_details
  endpoint:
    path: /hydrology/id/stations/{id}
    method: GET
    params:
      id: '{value}'
      _view: default
- name: list_monitoring_stations
  endpoint:
    path: /hydrology/id/stations
    method: GET
    params:
      _limit: '20'
- name: open_monitoring_stations
  endpoint:
    path: /hydrology/id/open/stations
    method: GET
    params:
      from: '{yyyy-mm-dd}'
      to: '{yyyy-mm-dd}'
      _view: default
- name: measure_readings
  endpoint:
    path: /hydrology/id/measures/{measure}/readings
    method: GET
    data_selector: readings
    params:
      measure: '{value}'
      date: '{yyyy-mm-dd}'
      min-date: '{yyyy-mm-dd}'
      mineq-date: '{yyyy-mm-dd}'
      max-date: '{yyyy-mm-dd}'
      maxeq-date: '{yyyy-mm-dd}'
      earliest: '{}'
      latest: '{}'
      _view: '{default|flow|full|min}'
- name: data_readings
  endpoint:
    path: /hydrology/data/readings
    method: GET
    data_selector: readings
    params:
      measure: '{id}'
      date: '{yyyy-mm-dd}'
      min-date: '{yyyy-mm-dd}'
      mineq-date: '{yyyy-mm-dd}'
      max-date: '{yyyy-mm-dd}'
      maxeq-date: '{yyyy-mm-dd}'
      earliest: '{}'
      latest: '{}'
      station: '{guid}'
      station.RLOIid: '{id}'
      station.wiskiID: '{id}'
      observationType: '{Qualified|Measured}'
      observedProperty: '{waterFlow|waterLevel|rainfall|groundwaterLevel|dissolved-oxygen|fdom|bga|turbidity|chlorophyll|conductivity|temperature|ammonium|nitrate|ph}'
      period: '{number}'
      _view: '{default|flow|full|min}'
- name: measure_readings
  endpoint:
    path: /hydrology/id/measures/{measure}/readings
    method: GET
    data_selector: readings
    params: {}
- name: data_readings
  endpoint:
    path: /hydrology/data/readings
    method: GET
    data_selector: readings
    params: {}
- name: asset_management
  endpoint:
    path: /asset-management
    method: GET
    data_selector: records
- name: bathing_waters
  endpoint:
    path: /bathing-waters
    method: GET
    data_selector: records
- name: catchment_data
  endpoint:
    path: /catchment-data
    method: GET
    data_selector: records
- name: ecology_and_fish
  endpoint:
    path: /ecology-and-fish
    method: GET
    data_selector: records
- name: flood_monitoring
  endpoint:
    path: /flood-monitoring
    method: GET
    data_selector: records
- name: hydrology
  endpoint:
    path: /hydrology
    method: GET
    data_selector: records
- name: public_registers
  endpoint:
    path: /public-registers
    method: GET
    data_selector: records
- name: rainfall
  endpoint:
    path: /rainfall
    method: GET
    data_selector: records
- name: rural_payments_agency_land
  endpoint:
    path: /rural-payments-agency-land
    method: GET
    data_selector: records
- name: tide_gauge
  endpoint:
    path: /tide-gauge
    method: GET
    data_selector: records
- name: water_quality_data_archive
  endpoint:
    path: /water-quality-data-archive
    method: GET
    data_selector: records
- name: river_flow
  endpoint:
    path: /hydrology/river-flow
    method: GET
    data_selector: data
    params: {}
- name: water_quality
  endpoint:
    path: /hydrology/water-quality
    method: GET
    data_selector: data
    params: {}
- name: Asset data requirements library
  endpoint:
    path: /asset-management/drl-app/revision/current/api/doc
    method: GET
- name: Asset information
  endpoint:
    path: /asset-management/doc/reference
    method: GET
- name: Bathing water signage
  endpoint:
    path: /bwq/signage
    method: GET
- name: Bathing water widget
  endpoint:
    path: /bwq/widget
    method: GET
- name: Bathing waters
  endpoint:
    path: /bwq/profiles/
    method: GET
- name: Biodiversity Gain Sites Register
  endpoint:
    path: /biodiversity-net-gain
    method: GET
- name: Catchment data explorer
  endpoint:
    path: /catchment-planning/api/docs#
    method: GET
- name: Drinking water
  endpoint:
    path: /farmers
    method: GET
- name: Ecology and fish explorer
  endpoint:
    path: /ecology/api
    method: GET
- name: Explore Marine Plans
  endpoint:
    path: /marine-plans-explorer
    method: GET
- name: Find Natural Capital Data
  endpoint:
    path: /natural-capital-ecosystem-assessment
    method: GET
- name: Flood plan explorer
  endpoint:
    path: /flood-planning/explorer/cycle-2/home
    method: GET
- name: Flood warning widgets
  endpoint:
    path: /flood-monitoring/doc/reference
    method: GET
- name: Future Water Resources Data Visualisation Tool
  endpoint:
    path: /future-water
    method: GET
- name: Hydrology
  endpoint:
    path: /hydrology/doc/reference
    method: GET
- name: MAGIC
  endpoint:
    path: /
    method: GET
- name: National Coastal Erosion Risk Mapping (NCERM)
  endpoint:
    path: /shoreline-planning/coastal-erosion
    method: GET
- name: Overheating in homes
  endpoint:
    path: /over-heating
    method: GET
- name: Public registers online
  endpoint:
    path: /public-register/view/api-reference
    method: GET
- name: Rainfall demonstrator
  endpoint:
    path: /flood-monitoring/assets/demo/index.html
    method: GET
- name: Reservoir flood maps
  endpoint:
    path: /reservoir-flood-maps/
    method: GET
- name: Rural Payments Agency land
  endpoint:
    path: /rpa/api-doc
    method: GET
- name: Shoreline Management Plans
  endpoint:
    path: /shoreline-planning
    method: GET
- name: Tide gauge readings
  endpoint:
    path: /flood-monitoring/tidegauge
    method: GET
- name: Waste carriers, brokers and dealers widget
  endpoint:
    path: /public-register/view/api-reference
    method: GET
- name: Water quality data archive
  endpoint:
    path: /water-quality/view/doc/reference
    method: GET
notes:
- The API supports a hard limit of 2,000,000 rows of data per-call.
- To request more data at a time, a batch API alternative is available.
- Uses linked data standards to improve data accessibility and interoperability.
- Data can be downloaded in CSV format or by using an API.
- Raw data is uploaded on a regular basis and replaced by checked data once plausibility
  checks have been completed.
errors:
- 'Limit exceeded: Please reduce the number of rows requested.'
- 'Request timeout: Consider breaking down the request.'
auth_info:
  mentioned_objects: []
client:
  base_url: http://environment.data.gov.uk/hydrology
source_metadata: null
